services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: dotalk_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    command: uv run gunicorn root.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/app
      - /app/.venv
      - media_data:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      REDIS_HOST: redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery:
    build: .
    command: uv run celery -A root worker -l info
    volumes:
      - .:/app
      - /app/.venv
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      REDIS_HOST: redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
  media_data:
